#!/usr/bin/env python
import os, re
from collections import namedtuple

header = """<!DOCTYPE html>
<!--
  DO NOT MODIFY THIS FILE BY HAND!

  It is generated by the mklibrary.py script at the top
  of the source tree.  Any changes you make in this file
  will be overwritten the next time mklibrary.py is run.

  -- Chris
-->
<html>

<head>
    <title>Library | MU G&G</title>
    <meta name="theme-color" content="#125D53">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="../contents/favicon.ico" type="image/x-icon" />
    <link rel="apple-touch-icon" sizes="57x57" href="../contents/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="../contents/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon" sizes="144x144" href="../contents/apple-touch-icon-144x144.png" />
    <link rel='stylesheet' href='../css/style.css' /> </head>

<body id="top">
<nav id="navContainer">
    <div id="anotherNavContainer">
        <a href="/"><img src="../contents/GG.svg" onerror="this.src='../contents/GG.png'; this.onerror=null;" /></a>
        <div id="nav">
            <ul>
                <li id="navHome" class="navMobileSpacer">
                    <p>-</p>
                </li>
                <!--Spacer for mobile nav-->
                <li id="navHome">
                    <p><a href="../">HOME</a></p>
                </li>
                <li>
                    <p><a class="currentPage" href="../library/">LIBRARY</a></p>
                </li>
                <li id="resourceDropdown">
                    <p><a href="../resources/">RESOURCES</a></p>
                    <ul id="subNav1">
                        <li>
                            <p><a target="_blank" href="https://www.github.com/mugeeksandgadgets">GITHUB</a></p>
                        </li>
                        <li>
                            <p><a href="../resources/software.html">SOFTWARE</a></p>
                        </li>
                        <li>
                            <p><a href="../resources/programming.html">PROGRAMMING</a></p>
                        </li>
                        <li>
                            <p><a href="../resources/reference.html">REFERENCE</a></p>
                        </li>
                    </ul>
                </li>
                <li>
                    <p><a href="../projects/">PROJECTS</a></p>
                </li>
                <li>
                    <p><a href="../about/">ABOUT</a></p>
                </li>
                <li>
                    <p><a href="../contact/">CONTACT</a></p>
                </li>
            </ul>
        </div>
    </div>
    <div id="navAccent">
        <h1 id="pgTitleD">#Library<span class="blinking-cursor">_</span></h1> </div>
</nav>
    <input type="checkbox" id="nav-trigger" class="nav-trigger" />
    <div class="clear-menu-btn"> <span class="top"></span> <span class="middle"></span> <span class="bottom"></span> <span class="circle"></span> </div>
    <div id="blueBlock">
        <div id="blueBlockContent"></div>
        <div id="blueBlockAccent">
            <h1 id="pgTitleM">#Library<span class="blinking-cursor">_</span></h1> </div>
    </div>
    <div id="wrapper">
        <div id="moverBlock"></div>
        <div id="content">
            <div class="seperator"></div>
            <main id="mainLibrary">
                <h1>THIS IS A PUBLIC BETA</h1>
                <h1>Coming soon the G&G Library</h1>"""
footer = """            </main>
        </div>
        <footer id="footer">
            <div id="footer_accent">
                <h1 id="MUGG">#GG<span class="blinking-cursor">_</span></h1> </div>
            <div id="footerContent">
                <div id="connect">
                    <h2>MU G&G</h2> </div>
                <div id="connectSocial">
                    <a target="_blank" href="../contents/socialIcons/Application.pdf"><img src="../contents/socialIcons/form.svg" onerror="this.src='../contents/socialIcons/form.png'; this.onerror=null;" /></a>
                    <a target="_blank" href="https://www.facebook.com/geeksandgadgetsclub"><img src="../contents/socialIcons/facebook.svg" onerror="this.src='../contents/socialIcons/facebook.png'; this.onerror=null;" /></a>
                    <a target="_blank" href="https://twitter.com/MUGandG"><img src="../contents/socialIcons/twitter.svg" onerror="this.src='../contents/socialIcons/twitter.png'; this.onerror=null;" /></a>
                    <a target="_blank" href="https://www.youtube.com/channel/UCKewnEQIee3QeGMmJXzo3uA"><img src="../contents/socialIcons/youtube.svg" onerror="this.src='../contents/socialIcons/youtube.png'; this.onerror=null;" /></a>
                    <a target="_blank" href="https://github.com/MUGeeksandGadgets"><img src="../contents/socialIcons/github.svg" onerror="this.src='../contents/socialIcons/github.png'; this.onerror=null;" /></a>
                </div>
            </div>
            <p id="bduke"><a target="_blank" href="https://bmduke1997.github.io/">A b.duke Site</a></p>
        </footer>
    </div>
</body>

</html>"""

folders = os.listdir(os.path.join('contents', 'books'))

genres = folders.copy()
genres.remove('covers')

with open(os.path.join('library', 'index.html'), 'w') as out:

    out.write(header)

    for genre in genres:
        out.write('<h3>%s</h3>' % genre)
        out.write('<div class="books">')

        books = os.listdir(os.path.join('contents', 'books', genre))

        for book in books:
            out.write('<a target="_blank" href="../contents/books/%s/%s">'
                  % (genre, book))
            covername = re.sub('\.[^\.]*$', '.jpg', book)
            out.write('<img src="../contents/books/covers/%s" />' % covername)
            out.write('</a>')

        out.write('</div>')

    out.write(footer)

print('=> Page written to ./library/index.html')
